export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_FILTER_PRODUCTS = 'GET_FILTER_PRODUCTS';
export const SET_ERROR_INFO = 'SET_ERROR_INFO';